### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file

Can you point out any places where I can refactor or make my code more simple please.
I tried to make a basic init function but failed 😢

**Comment by chrisvfritz** [comment]
Wow, this looks really great! I only see one area for improvement and that would be to combine the `updateParagraph` and `updateHTML` functions into a single function to rule them all. ✨💍✨ 

This will also make your code a little easier to maintain. If you look right now, you actually have code building the same HTML _twice_. That means whenever you wanted to make a change in the future (e.g. changing the `h2` to an `h1`, you'd have two places to do it. If you forgot one time, it would create a bug! Instead, try to reuse the string by assigning it to a _variable_. 🙂 

Let me know if you get what I mean. Otherwise, I'm happy to clarify!

**Comment by GriffinMartin** [comment]
@chrisvfritz 
Refactored and simplified my code, hopefully this looks good! 
Thanks for the tips 👍

**Comment by chrisvfritz** [comment]
Fantastic! This code is without flaw. 👏 :shipit:

**Comment by GriffinMartin** [comment]
@chrisvfritz 
Holy shit that was fast lol. Thanks
